- name: Set timezone
  include_tasks: tasks/set_timezone.yaml
  when: enable_set_timezone

- name: Set hostname
  include_tasks: tasks/set_hostname.yaml
  when: enable_set_hostname

- name: Update /etc/hosts
  template: src=templates/hosts dest=/etc/hosts owner=root group=root mode=0644 force=yes unsafe_writes=yes

- name: Run secure_ssh.sh script
  script: files/secure_ssh.sh

- name: Configure logrotate and journald settings
  include_tasks: configure_logrotate.yaml
  when: rsyslog_log_rotation.enable

- name: Install packages
  script: files/install-packages.sh
  when: enable_install_packages and (ansible_facts['distribution'] == "Ubuntu") or (ansible_facts['distribution'] == "Debian")

#- name: Include GPU Configuration
#  include_tasks: include_gpu.yaml
#  when: (ansible_facts['distribution'] == "Ubuntu") or (ansible_facts['distribution'] == "Debian")
#  tags: 
#    - k3s
#    - gpu
#    - nvidia

#- name: enable ip_forward
#  shell: 'echo "net.ipv4.ip_forward = 1" >> /etc/sysctl.conf; echo "net.ipv4.conf.all.proxy_arp = 1" >> /etc/sysctl.conf ; sysctl -p /etc/sysctl.conf'


#- name: Install packages
#  shell: "yum makecache && yum install -y audit container-selinux"
#  when: (ansible_facts['distribution'] != "Ubuntu") or (ansible_facts['distribution'] != "Debian")
