- name: Check if systemctl is available
  command: which systemctl
  register: systemctl_check
  ignore_errors: true

- name: Set hostname using systemctl if available
  shell: "systemctl set-hostname {{ ansible_fqdn }}"
  when: systemctl_check.rc == 0

- name: Set hostname using hostname -F if systemctl is not available
  shell: "hostname -F /etc/hostname"
  when: systemctl_check.rc != 0
