- name: Add NVIDIA device plugin Helm repository
  shell: |
    helm repo add nvidia-device-plugin https://nvidia.github.io/k8s-device-plugin
    helm repo update

- name: Install NVIDIA device plugin Helm chart
  command: helm install nvidia-device-plugin nvidia-device-plugin/nvidia-device-plugin --namespace kube-system
