enable_set_timezone: true       # 默认启用 Set timezone
enable_set_hostname: true       # 默认启用 Set hostname
enable_install_packages: false  # 默认不安装额外的软件包
enable_all_hosts_update: false  # 默认不更新所有主机的条目
rsyslog_log_rotation:           # 可选的日志管理配置
  enable: true                  # 启用 rsyslog 日志管理
  rotate_count: 4               # 默认保留的日志文件数量
  rotate_frequency: weekly      # 默认每周轮换, 可选：daily, hourly
  max_log_size: 100M            # 默认日志文件最大大小
