services:
  registry:
    image: hub.deepflow.yunshan.net/dev/registry:latest
    container_name: registry
    restart: always
    network_mode: host
    volumes:
      - /usr/local/deepflow/registry:/var/lib/registry
      - /opt/deepflow-registry/config/deepflow-registry.yaml:/etc/docker/registry/config.yml
      - /etc/ssl/onwalk.net.pem:/etc/docker/registry/domain.crt
      - /etc/ssl/onwalk.net.key:/etc/docker/registry/domain.key

