- name: Base checks
  hosts: all
  gather_facts: false
  tasks:
    - name: Echo hostname
      shell: hostname

    - name: Run CPU count script
      script: ./example/nproc.sh

    - name: Show uptime via command
      command: /usr/bin/uptime

    - name: Ensure uptime visible
      shell: pwd
