- name: Base checks
  hosts: all
  gather_facts: false
  tasks:
    - name: Echo hostname
      shell: hostname

    - name: Run CPU count script
      script: ./example/nproc.sh

    - name: Ensure uptime visible
      shell: pwd
