group: vpn-gateway
nameserver:
  - 127.0.0.53
extra_resolv_config:
  - "options edns0 trust-ad"
  - "search ap-northeast-1.compute.internal"
gateway:
  private_key: "{{ host_keys.global_gateway_private_key }}"
  network: "10.255.0.1/32"
  listen_port: 51820
  tunnel: "wg0"
  interface: "eth0"
  mtu: 1200
  postup_rules:
    - "iptables -A FORWARD -i {{ gateway.tunnel }} -j ACCEPT"
    - "iptables -t nat -A POSTROUTING -o {{ gateway.interface }} -j MASQUERADE"
    - "/usr/local/bin/udp2raw -s -l 0.0.0.0:2443 -r 52.196.108.28:51820 -k \"udp2raw\" --raw-mode faketcp -a --log-level 3 > /tmp/udp.log &"
  postdown_rules:
    - "iptables -D FORWARD -i {{ gateway.tunnel }} -j ACCEPT"
    - "iptables -t nat -D POSTROUTING -o {{ gateway.interface }} -j MASQUERADE"
    - "killall udp2raw || true"
  peers:
    - public_key: "{{ host_keys.global_k3s_server_db_public_key }}"
      allowed_ips: "10.255.0.2/32"
      persistent_keepalive: 25
    - public_key: "{{ host_keys.global_k3s_server_public_key }}"
      allowed_ips: "10.255.0.3/32"
      persistent_keepalive: 25
    - public_key: "{{ host_keys.desktop_macbook_public_key }}"
      allowed_ips: "10.255.0.200/32"
      persistent_keepalive: 25
    - public_key: "{{ host_keys.cn_gateway_public_key }}"
      allowed_ips: "10.254.0.0/16, 10.255.0.0/16"
      endpoint: "127.0.0.1:51831"
      persistent_keepalive: 25
