- name: Add NVIDIA repository
  shell: |
    #add-apt-repository -y ppa:graphics-drivers
    distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
    curl -s -L https://nvidia.github.io/nvidia-container-runtime/$distribution/nvidia-container-runtime.list | tee /etc/apt/sources.list.d/nvidia-container-runtime.list
    curl -s -L https://nvidia.github.io/nvidia-container-runtime/gpgkey | apt-key add -
    apt-get update

- name: Install NVIDIA driver and container runtime
  apt:
    name: 
      - nvidia-modprobe
      - nvidia-driver-535
      - nvidia-headless-535
      - nvidia-container-runtime
    state: present
    update_cache: yes

- name: Output results
  debug:
    msg: "{{ command_result.stdout_lines }}"
  register: command_result

- name: Test nvidia-smi
  shell: |
    sudo ctr image pull docker.io/nvidia/cuda:12.1.1-base-ubuntu22.04
    sudo ctr run --rm -t --runc-binary=/usr/bin/nvidia-container-runtime \
      --env NVIDIA_VISIBLE_DEVICES=all \
      docker.io/nvidia/cuda:12.1.1-base-ubuntu22.04 \
      cuda-11.6.2-base-ubuntu20.04 \
      nvidia-smi
  register: nvidia_smi_output

- debug:
    var: nvidia_smi_output.stdout_lines
