- name: Gather network interface information and display details
  hosts: all
  gather_facts: yes
  tasks:
    - name: Display interface details
      ansible.builtin.debug:
        msg: |
          Interface: "{{ item }}"
          Status: "{{ 'UP' if hostvars[inventory_hostname]['ansible_' + item].active else 'DOWN' }}"
          IP Address: "{{ hostvars[inventory_hostname]['ansible_' + item].ipv4.address if hostvars[inventory_hostname]['ansible_' + item].ipv4 is defined else 'N/A' }}"
          Netmask: "{{ hostvars[inventory_hostname]['ansible_' + item].ipv4.netmask if hostvars[inventory_hostname]['ansible_' + item].ipv4 is defined else 'N/A' }}"
          Route: "To be manually determined or fetched with additional tasks"
      loop: "{{ ansible_facts.interfaces }}"
      when: "'ens' in item or 'cni' in item"
