---
- name: Gather specific network interface information and display details
  hosts: all
  gather_facts: yes
  tasks:
    - name: Display details for interfaces starting with ens or cni
      ansible.builtin.debug:
        msg: |
          Interface: {{ item.key }}
          Status: {{ 'UP' if item.value.active else 'DOWN' }}
          IP Address: {{ item.value.ipv4.address if item.value.ipv4 is defined else 'N/A' }}
          Netmask: {{ item.value.ipv4.netmask if item.value.ipv4 is defined else 'N/A' }}
          Route: {{ item.value.ipv4.network if item.value.ipv4 is defined else 'N/A' }}
      loop: "{{ ansible_facts.interfaces | dict2items }}"
      when: item.key | regex_search('^(ens|cni)')
      loop_control:
        label: "{{ item.key }}"
