name: Build and Release Xconfig Agent

on:
  pull_request:
    paths:
      - 'XconfigAgent/**'
      - '.github/workflows/build-agent-release.yml'
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  build:
    name: Build cw-agent binaries
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [ubuntu, macos, windows]
        arch: [amd64, arm64]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build binary
        working-directory: XconfigAgent
        run: |
          mkdir -p dist
          cargo build --release
          if [[ "${{ matrix.os }}" == "windows" ]]; then
            cp target/release/cw-agent.exe dist/cw-agent-${{ matrix.os }}-${{ matrix.arch }}.exe
          else
            cp target/release/cw-agent dist/cw-agent-${{ matrix.os }}-${{ matrix.arch }}
          fi
        shell: bash

      - name: Compress and checksum
        working-directory: XconfigAgent/dist
        run: |
          if [[ "${{ matrix.os }}" == "windows" ]]; then
            powershell -Command "Compress-Archive -Path cw-agent-${{ matrix.os }}-${{ matrix.arch }}.exe -DestinationPath cw-agent-${{ matrix.os }}-${{ matrix.arch }}.zip"
            powershell -Command "Get-FileHash cw-agent-${{ matrix.os }}-${{ matrix.arch }}.zip -Algorithm SHA256 | ForEach-Object { \"$($_.Hash)  cw-agent-${{ matrix.os }}-${{ matrix.arch }}.zip\" } | Out-File -Encoding ASCII -FilePath cw-agent-${{ matrix.os }}-${{ matrix.arch }}.sha256"
          else
            tar -czvf cw-agent-${{ matrix.os }}-${{ matrix.arch }}.tar.gz cw-agent-${{ matrix.os }}-${{ matrix.arch }}
            shasum -a 256 cw-agent-${{ matrix.os }}-${{ matrix.arch }}.tar.gz > cw-agent-${{ matrix.os }}-${{ matrix.arch }}.sha256
          fi
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cw-agent-${{ matrix.os }}-${{ matrix.arch }}
          path: |
            XconfigAgent/dist/cw-agent-${{ matrix.os }}-${{ matrix.arch }}*

  test:
    name: Test Rust Agent (Linux only)
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Run cargo test
        working-directory: XconfigAgent
        run: cargo test

  publish-release:
    name: Publish Daily Release
    needs: [build, test]
    runs-on: ubuntu-latest
    env:
      tag_name: daily-agent-${{ github.run_id }}
      release_name: Daily Build cw-agent - ${{ github.run_number }}

    steps:
      - uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: release-artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.tag_name }}
          name: ${{ env.release_name }}
          prerelease: true
          files: |
            release-artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
