name: Build Offline IaC Installer

on:
  push:
    paths:
      - 'scripts/iac-installer.sh'
      - '.github/workflows/build-iac-offline-installer.yml'
  workflow_dispatch:

jobs:
  build-iac-installer:
    strategy:
      matrix:
        arch: [amd64, arm64]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Prepare offline directory structure
        run: |
          for os in linux macos windows; do
            mkdir -p offline-iac/tools/${os}/amd64
            mkdir -p offline-iac/tools/${os}/arm64
          done
          mkdir -p offline-iac/scripts offline-iac/manifests

      - name: Download Pulumi/Ansible/Terraform binaries & plugins
        run: |
          set -e
          ARCH=${{ matrix.arch }}
          PULUMI_VERSION=3.112.0
          TERRAFORM_VERSION=1.6.6
          ANSIBLE_VERSION=7.5.0
          mkdir -p offline-iac/plugins/{pulumi,terraform,ansible}

          # ------------------------------
          # Pulumi CLI for all platforms
          for OS in linux darwin windows; do
            OUT_OS=$OS
            [[ "$OS" == "darwin" ]] && OUT_OS="macos"
            curl -L -o offline-iac/tools/${OUT_OS}/${ARCH}/pulumi-${PULUMI_VERSION}.tar.gz \
              https://get.pulumi.com/releases/sdk/pulumi-v${PULUMI_VERSION}-${OS}-${ARCH}.tar.gz
          done

          # Pulumi Plugins (AWS, GCP, Azure, Alibaba)
          pulumi plugin install resource aws v6.50.0
          pulumi plugin install resource gcp v6.62.0
          pulumi plugin install resource azure v5.60.0
          cp -r ~/.pulumi/plugins/* offline-iac/plugins/pulumi/

          # Terraform CLI for all platforms
          for OS in linux darwin windows; do
            OUT_OS=$OS
            [[ "$OS" == "darwin" ]] && OUT_OS="macos"
            curl -L -o offline-iac/tools/${OUT_OS}/${ARCH}/terraform.zip \
              https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_${OS}_${ARCH}.zip
          done

          # Terraform Providers (AWS, GCP, Azure, Alibaba)
          mkdir -p terraform-provider-cache
          echo 'provider "aws" {}' > main.tf
          terraform init -plugin-dir=terraform-provider-cache || true
          cp -r terraform-provider-cache/* offline-iac/plugins/terraform/

          # Ansible pip wheels
          python3 -m pip download ansible==${ANSIBLE_VERSION} -d offline-iac/tools/linux/${ARCH}/ --only-binary=:all:
          python3 -m pip download ansible==${ANSIBLE_VERSION} -d offline-iac/tools/macos/${ARCH}/ --only-binary=:all:
          python3 -m pip download ansible==${ANSIBLE_VERSION} -d offline-iac/tools/windows/${ARCH}/ --only-binary=:all:

          # Ansible Collections
          ansible-galaxy collection download amazon.aws -p offline-iac/plugins/ansible
          ansible-galaxy collection download google.cloud -p offline-iac/plugins/ansible
          ansible-galaxy collection download azure.azcollection -p offline-iac/plugins/ansible

      - name: Copy installer script
        run: |
          cp scripts/iac-installer.sh offline-iac/scripts/
          chmod +x offline-iac/scripts/iac-installer.sh

      - name: Package offline installer
        run: |
          cd offline-iac
          tar czvf ../offline-setup-iac-${{ matrix.arch }}.tar.gz ./
          cd ..

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: offline-setup-iac-${{ matrix.arch }}
          path: offline-setup-iac-${{ matrix.arch }}.tar.gz

  test-offline-installer:
    needs: build-iac-installer
    strategy:
      matrix:
        arch: [amd64, arm64]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download offline installer artifact for ${{ matrix.arch }}
        uses: actions/download-artifact@v4
        with:
          name: offline-setup-iac-${{ matrix.arch }}
          path: offline-test

      - name: Extract offline installer
        run: |
          cd offline-test
          tar -xzvf offline-setup-iac-${{ matrix.arch }}.tar.gz
          cd ..

      - name: Install dependencies for test
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip python3-pip

      - name: Test offline installer
        run: |
          cd offline-test
          bash scripts/iac-installer.sh

      - name: Check Pulumi version
        run: |
          pulumi version

      - name: Check Terraform version
        run: |
          terraform version

      - name: Check Ansible version
        run: |
          ansible --version || true

  publish-release:
    needs: test-offline-installer
    runs-on: ubuntu-latest
    env:
      tag_name: offline-iac-${{ github.run_number }}

    steps:
      - uses: actions/checkout@v4

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.tag_name }}
          release_name: Offline IaC Installer ${{ env.tag_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download amd64 artifact
        uses: actions/download-artifact@v4
        with:
          name: offline-setup-iac-amd64
          path: release-artifacts

      - name: Download arm64 artifact
        uses: actions/download-artifact@v4
        with:
          name: offline-setup-iac-arm64
          path: release-artifacts

      - name: Upload offline installers to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.tag_name }}
          files: |
            release-artifacts/offline-setup-iac-amd64.tar.gz
            release-artifacts/offline-setup-iac-arm64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
