name: Generate and Release Self-Signed SSL Certificates

on:
  push:
    tags:
      - "release-*"
  pull_request:
    paths:
      - '.github/workflows/self-signed-ssl-cert-workflow.yml'
  workflow_dispatch:
    branches:
      - main

jobs:
  generate-cert:
    runs-on: ubuntu-latest
    env:
      DOMAIN: "kube.registry.local"
      VALID_DAYS: "3650"
      OUTPUT_DIR: "ssl_certificates"
      tag_name: ${{ github.ref_name }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Ensure script is executable
        run: chmod +x scripts/generate_ssl.sh

      - name: Debug Inputs
        run: |
          echo "Inputs received from GitHub Actions:"
          echo "DOMAIN: $DOMAIN"
          echo "VALID_DAYS: $VALID_DAYS"
          echo "TAG_NAME: $tag_name"

      - name: Generate Self-Signed SSL Certificate
        run: scripts/generate_ssl.sh "$DOMAIN" "$VALID_DAYS" "$OUTPUT_DIR"
        shell: bash

      - name: Package Self-Signed Certificates
        run: |
          tar -czvf ssl_certificates.tar.gz -C "$OUTPUT_DIR" .

      - name: Upload Self-Signed Certificates as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: self-signed-ssl-certificates
          path: ssl_certificates.tar.gz

      - name: Release Self-Signed SSL Certificates
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ env.tag_name }}
          name: "Self-Signed SSL Certificates for ${{ env.DOMAIN }}"
          draft: false
          prerelease: false
          files: ssl_certificates.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cleanup Old Self-Signed Certificates
        run: rm -rf "$OUTPUT_DIR" ssl_certificates.tar.gz
